### ISSUE TITLE
java.sql.SQLException: spy.properties not found in classpath

### ISSUE THREAD

**Issue by suxg003** [songwie/task#3]
host].[/] - Initializing Spring embedded WebApplicationContext
2016-03-11 14:35:30 ERROR com.alibaba.druid.pool.DruidDataSource - dataSource in
it error
java.sql.SQLException: spy.properties not found in classpath
        at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:536)
        at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:597)

```
    at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.
```

java:934)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.
java:930)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.
java:102)
        at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionPr
oviderImpl.getConnection(DatasourceConnectionProviderImpl.java:139)
        at org.hibernate.engine.jdbc.internal.JdbcServicesImpl$ConnectionProvide
rJdbcConnectionAccess.obtainConnection(JdbcServicesImpl.java:279)
        at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcSer
vicesImpl.java:124)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.conf
igureService(StandardServiceRegistryImpl.java:111)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initialize
Service(AbstractServiceRegistryImpl.java:234)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService
(AbstractServiceRegistryImpl.java:206)
        at org.hibernate.cfg.Configuration.buildTypeRegistrations(Configuration.
java:1887)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.jav
a:1845)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.per
form(EntityManagerFactoryBuilderImpl.java:857)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.per
form(EntityManagerFactoryBuilderImpl.java:850)
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceI
mpl.withTccl(ClassLoaderServiceImpl.java:425)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build
(EntityManagerFactoryBuilderImpl.java:849)
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvi
der.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.ja
va:60)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.cr
eateNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPro
pertiesSet(AbstractEntityManagerFactoryBean.java:318)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getOb
ject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
y.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:302)

**Comment by songwie** [comment]
这是数据库启动时候用的一个数据库驱动的包 配置注意显示参数用的你可以把驱动包改成原生的

**Comment by songwie** [comment]
datasource.druid.driverClassName=com.mysql.jdbc.Driver

**Comment by songwie** [comment]
你好！
     spy.properties 这个配置文件是dev 环境下的一个数据库驱动包的配置文件你可以切换到原始的mysql驱动
1.    java -jar task-web-1.0.1-SNAPSHOT.war --datasource.druid.driverClassName=datasource.druid.driverClassName=com.mysql.jdbc.Driver
1. 或者启动的时候配置test环境的数据库 环境，修改配置文件：
   application-test.properties

这一部分

然后启动时候：
 java -jar task-web-1.0.1-SNAPSHOT.war --spring.profiles.active=test
1. 或者执行执行
   nohup java -Xms500m -Xmx500m -Xmn100m -XX:PermSize=64m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+UseCMSCompactAtFullCollection -XX:CMSFullGCsBeforeCompaction=0 -XX:CMSInitiatingOccupancyFraction=70 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1986 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -jar task-web.war --spring.profiles.active=test --datasource.druid.url=jdbc:mysql://127.0.0.1:3306/task --datasource.druid.username=root --datasource.druid.password=root &

上面根据自己环境修改自己的数据库地址

关于集群启动的因为模式就是数据库模式的集群，直接启动多个服务，服务之间或自动集群同步的，不需要关系内部实现
